### PR TITLE
fix a small bug in unwrapping an erroneous file reads. closes #35.

### LINKED ISSUE #35: test torn pages on log
1. write garbage to log after valid entries
1. ensure read on valid entries suceeds
1. ensure read on garbage fails
1. ensure that during recovery, we detect the torn page and allow new entries to reuse the garbage space
1. ensure that the new entries, and old valid entries are valid before shutting down
1. recove again, ensure all valid entries are readable

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

File: src/log/lss.rs [hunk 1]
```diff
@@ -207,11 +207,11 @@ impl Log for LockFreeLog {
     }
 
     /// deallocates the data part of a log id
-    fn punch_hole(&self, id: LogID) {
+    fn punch_hole(&self, id: LogID) -> std::io::Result<()> {
         // we zero out the valid byte, and use fallocate to punch a hole
         // in the actual data, but keep the len for recovery.
         let cached_f = self.config().cached_file();
         let mut f = cached_f.borrow_mut();
-        punch_hole(&mut f, id).unwrap();
```
Comment (spacejam) [inline src/log/lss.rs]: this was the bug, it failed to read the full header in a corrupted file

File: tests/test_log.rs [hunk 2]
```diff
@@ -310,55 +317,88 @@ fn prop_log_works(ops: OpVec) -> bool {
...
+
+                    use std::os::unix::io::AsRawFd;
+
+                    let cached_f = config.cached_file();
+                    let f = cached_f.borrow_mut();
+                    use libc::ftruncate;
+                    let fd = f.as_raw_fd();
+
+                    unsafe {
+                        ftruncate(fd, new_len as i64);
```
Comment (spacejam) [inline tests/test_log.rs]: this simulates simple file corruption in a crash by cutting down the file
